{% set name = "pygam" %}
{% set version = "0.9.1" %}
{% set sha256 = "a321a017bf485ed93fc6233e02621f8e7eab3d4f8971371c9ae9e079c55be01d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-patch-versions.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - poetry
  run:
    - python >=3.6
    - numpy
    - scipy >=0.17
    - progressbar2
    - future

test:
  imports:
    - pygam
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dswah/pyGAM
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Generalized Additive Models in Python
  description: |
    pyGAM is a library for training generalized additive models in Python.
    GAMs are powerful and interpretable, which makes it easy to fit
    complex data while still being able to understand the model.
  dev_url: https://github.com/dswah/pyGAM

extra:
  recipe-maintainers:
    - dswah
    - jtilly
