{% set name = "pygam" %}
{% set version = "0.10.1" %}
{% set sha256 = "0d7c0ba235919dfadfe2347ca89c4fed5879acd428a944633959a8e0cc3e0311" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-patch-versions.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
    - poetry-dynamic-versioning
  run:
    - python >={{ python_min }}
    - numpy
    - scipy >=1.10
    - progressbar2
    - future

test:
  imports:
    - pygam
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/dswah/pyGAM
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Generalized Additive Models in Python
  description: |
    pyGAM is a library for training generalized additive models in Python.
    GAMs are powerful and interpretable, which makes it easy to fit
    complex data while still being able to understand the model.
  dev_url: https://github.com/dswah/pyGAM

extra:
  recipe-maintainers:
    - dswah
    - jtilly
    - fkiraly
    - marrov
