{% set name = "pygam" %}
{% set version = "0.6.1" %}
{% set sha256 = "ebcae96d033a87eda7bfe157e27a08d7bd457a33aafb8b3bae69b6960a0b20dd" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy >=0.17
    - progressbar2
    - future

test:
  imports:
    - pygam

about:
  home: https://github.com/dswah/pyGAM
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: Generalized Additive Models in Python
  description: |
    pyGAM is a library for training generalized additive models in Python.
    GAMs are powerful and interpretable, which makes it easy to fit
    complex data while still being able to understand the model.
  dev_url: https://github.com/dswah/pyGAM

extra:
  recipe-maintainers:
    - dswah
