{% set name = "pygam" %}
{% set version = "0.6.3" %}
{% set sha256 = "f7be383545b45d2f46a8bf9f0f66467c450f35d4d99a80f99fe33ec6c85fa7d9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy >=0.17
    - progressbar2
    - future

test:
  imports:
    - pygam

about:
  home: https://github.com/dswah/pyGAM
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: Generalized Additive Models in Python
  description: |
    pyGAM is a library for training generalized additive models in Python.
    GAMs are powerful and interpretable, which makes it easy to fit
    complex data while still being able to understand the model.
  dev_url: https://github.com/dswah/pyGAM

extra:
  recipe-maintainers:
    - dswah
